pass target_interval_list to collect_metrics
Passing the bed file resulted in the error:
java.lang.IllegalStateException: Interval list file must contain header.

Switching to use interval_list based on comments in
https://gatkforums.broadinstitute.org/gatk/discussion/6973/bait-interval-and-target-interval-file-format-issue